### ISSUE TITLE
rqcReadQualityPlot function breaks when reshape package is loaded

### ISSUE THREAD

**Issue by Welliton309** [labbcb/Rqc#9]
Rqc depends on `reshape2` package. When `reshape` package (version 1) are loaded on environment, R runs `melt` function incorrectly. This issue breaks Rqc's plot functions.

**Comment by Welliton309** [comment]
Rqc no longer use reshape2 package.

**Comment by benilton** [comment]
was this a recommendation by Hadley?

**Comment by Welliton309** [comment]
He didn't answer the issue. However, now Rqc creates tidy data frames during processing (rqcQA function), melt function is no longer needed.
